In [1]:
%matplotlib inline
import numpy as np
from matplotlib_inline import backend_inline
from d2l import torch as d2l

/home/m/miniconda3/envs/d2l/lib/python3.9/site-packages/torch/cuda/__init__.py:546: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [11]:
import torch

In [12]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [13]:
# Can also create x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
x.grad # The gradient is None by default

In [14]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [15]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [16]:
x.grad == 4 * x

tensor([True, True, True, True])

In [20]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [ ]:
# detaching

x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [ ]:
# 2.5.4 Gradients and Python Control Flow
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0: 
        c = b
    else:
        c = 100 * b
    return c



In [26]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [28]:
a.grad == d / a

tensor(True)